[m-files.tool]
rest-api-url = "https://<youer-vault-DNS-prefix>.cloudvault.m-files.com/REST/"
username = "<your-admin-username"
password = "<your-admin-password>"
vault = "{<your-optional-vault-GUID-if-not-given-first-vault-GUID-used>}"
log-level = "INFO"
tika-server-url = "https://<your-tika-server-url>"
